@extends('layouts.landing')

@section('content')
    @include('partials.landing.what-we-are')
    @include('partials.landing.trust')
    @include('partials.landing.partners')
    @include('partials.landing.why-us')
    @include('partials.landing.stats-moocs')
    @include('partials.landing.how-it-works-mvp')
    @include('partials.landing.stats-demand')
    @include('partials.landing.how-it-works')
    @include('partials.landing.team')
    @include('partials.landing.subscribe')
    @include('partials.landing.roadmap')
    @include('partials.landing.subscribe-alt')
@endsection